url: https://www.cyberg.online
baseurl: /

# Site settings
title: Cyberg Online
email: support@cyberg.online
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Sarah Munson
  pic: sarah-munson
  position: Lead Designer
  social:
    # - title: twitter
    #   url: #
    # - title: facebook
    #   url: #
    # - title: stack-overflow
    #   url: #

- name: Vin Kim
  pic: vin-kim
  position: Lead Developer
  social:
    # - title: twitter
    #   url: #
    # - title: facebook
    #   url: #
    # - title: linkedin
    #   url: #

- name: Michael Morris
  pic: 2
  position: Senior Software Engineer
  social:
    # - title: twitter
    #   url: #
    # - title: facebook
    #   url: #
    # - title: linkedin
    #   url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url:
  - title: facebook
    url:
  - title: github
    url: https://github.com/cybergonline

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
